apiVersion: v1
data:
  modPenModulos.sh: {{ tpl (.Files.Get "apoio/scripts/modulos.sh") . | b64enc }}
  modPenModseipen.sh: {{ tpl (.Files.Get "apoio/scripts/mod-sei-pen/mod-sei-pen.sh") . | b64enc }}
kind: Secret
metadata:
  name: se-php-install-files
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
type: Opaque