apiVersion: v1
data:
  seiConfiguracao.php: {{ tpl (.Files.Get "apoio/conf/sistema/sei/config/ConfiguracaoSEI.php") . | b64enc }}
  sipConfiguracao.php: {{ tpl (.Files.Get "apoio/conf/sistema/sip/config/ConfiguracaoSip.php") . | b64enc }}
  modPenCertificado.pem: {{ .Values.app.modulo_pen_certificado_base64 }}
  modPenConfiguracaoModPen.php: {{ tpl (.Files.Get "apoio/conf/sistema/sei/config/mod-pen/ConfiguracaoModPEN.php") . | b64enc }}
  modAssinatura.php: {{ tpl (.Files.Get "apoio/conf/sistema/sei/config/mod-assinatura-eletronica/ConfiguracaoModAssinaturaEletronica.php") . | b64enc }}
kind: Secret
metadata:
  name: se-php-files
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
type: Opaque