apiVersion: v1
data:
  dbcreate.sh: {{ tpl (.Files.Get "apoio/scripts/dbcreate-mariadb.sh") . | b64enc }}
  instalar.sh: {{ tpl (.Files.Get "apoio/scripts/instalar.sh") . | b64enc }}
  sip-config-openldap.php: {{ tpl (.Files.Get "apoio/scripts/ldap/sip-config-openldap.php") . | b64enc }}
  gerarchaves.sh: {{ tpl (.Files.Get "apoio/scripts/gerarchaves.sh") . | b64enc }}
  gerarchaves.php: {{ tpl (.Files.Get "apoio/scripts/gerarchaves.php") . | b64enc }}
  modPenModulos.sh: {{ tpl (.Files.Get "apoio/scripts/modulos.sh") . | b64enc }}
  modPenModseipen.sh: {{ tpl (.Files.Get "apoio/scripts/mod-sei-pen/mod-sei-pen.sh") . | b64enc }}
kind: Secret
metadata:
  name: se-php-install-files
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
type: Opaque