apiVersion: apps/v1
kind: Deployment
metadata:
  name: agendador
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      servico: agendador
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        servico: agendador
        {{- include "sei-app.labels" . | nindent 8 }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm-php
            optional: false
        - secretRef:
            name: se-php
            optional: false
        image: ghcr.io/pengovbr/sei-helm/php-cron:0.5.0
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        name: sei-app
        startupProbe:
          exec:
            command:
            - sh
            - '-c'
            - ls /var/lib/sei/dbcontrol/install-initial.ok
          failureThreshold: 100
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/lib/sei
          name: vol-sei
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-sei
        persistentVolumeClaim:
          claimName: vol-sei