################################################################################
# Alpine Oficial - apenas redundancia do repo oficial
################################################################################

ARG ALPINE_ORIGINAL_VERSION=3.21

FROM alpine:${ALPINE_ORIGINAL_VERSION}

RUN apk add --no-cache \
    tzdata