; Arquivo sugestivo. Sera sobrescrito pelo seu file no helm

[php]
; Parâmetros recomendados no Manual de Instalação
include_path = ".:/php/includes:/opt/infra/infra_php"
default_charset = "iso-8859-1"
session.gc_maxlifetime = 28800
short_open_tag = On
default_socket_timeout = 60
max_input_vars = 2000
magic-quotes-gpc = 0
magic_quotes_runtime = 0
magic_quotes_sybase = 0
post_max_size = 1200M
upload_max_filesize = 1024M

log_errors = On
error_reporting = E_ALL
display_errors = Off
display_startup_errors = On
html_errors = On
always_populate_raw_post_data = -1

fastcgi.logging = Off

;zend_extension=xdebug.so
;xdebug.mode=debug
;xdebug.start_with_request=yes
;xdebug.client_host=192.168.2.100
;xdebug.client_port=9003
;xdebug.remote_handler=dbgp
;xdebug.discover_client_host=1
;xdebug.idekey=default

[Session]
session.save_handler = memcache
session.save_path = memcached:11211

[opcache]
opcache.enable=1
; In a containerized environment where code doesn't change during runtime, disable timestamp validation for performance.
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.interned_strings_buffer=32
opcache.fast_shutdown=1