apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  externalName: memcached.{{ .Values.app.memcachednamespace }}.svc.cluster.local.
  sessionAffinity: None
  type: ExternalName
