apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: fcgi
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    servico: php
