apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-solr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  {{- with .Values.solr.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}