apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-solr
  labels:
    {{- include "sei-solr.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  {{- with .Values.solr.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}