app:

    # informe a classe do pvc onde serao criados os volumes do SEI
    # deve estar pre-instalado no seu kubernetes um provisionador nfs
    # gluster ou outro. No caso do docker-desktop ja existe um provisionador
    # automatico que cria uma pasta na vm do host ou do linux wsl. Para isso deixe
    # o storageclass vazio
    # caso contrario tera q criar o pv manualmente
    storage:
        #storageClass: nfs-client
        storageClass: ""

    imagePhp:
        repository: ghcr.io/pengovbr/sei-helm/php
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry

    imageCron:
        repository: ghcr.io/pengovbr/sei-helm/php-cron
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry

    imageWeb:
        repository: ghcr.io/pengovbr/sei-helm/apache
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry

    imageInstall:
        repository: ghcr.io/pengovbr/sei-helm/php-install
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry


    pvc:
      # caso queira usar um seletor no pvc
      # para fazer o bind no PV, use como ex abaixo
      # seletor atual desabilidado
      selector: {}
      # para habilitar seque exemplo abaixo
      # Ex:
      # selector:
      #   matchLabels:
      #     purpose: app



    nameOverride: ""
    fullnameOverride: ""

    ingress:
        proxyBodySize: 510m

        # Nome do secret com o certificado TLS para o ingress.
        # Crie esse secret com antecedencia para o ingress caso
        # nao possua uma ferramenta emissora.
        # Adicione no formato crt e key padrao para ingress do kube
        tls_secret_name: "mysecret"

        # anotacoes opcionais, renomeie de zopcionais para opcionais,
        # apos isso, todos as anotacoes listadas serao publicadas no ingress
        # alem dos exemplos abaixo, vc pode informar as suas especificas
        zopcionais:
            #cert-manager.io/cluster-issuer: letsencrypt-dth
            #kubernetes.io/ingress.class: nginx
            #kubernetes.io/tls-acme: "true"
            #nginx.ingress.kubernetes.io/affinity: cookie1
            #nginx.ingress.kubernetes.io/session-cookie-name: PIINGRESSAFFINITY

    # endereco (nome) onde encontram-se os servicos externos
    servicoExterno:
        db: dbhostname
        jod: jodhostname
        solr: solrhostname
        memcached: memcachedhostname
        # nome ou ip
        mail: mailhostname
        ldap: ldaphostname

    tz: America/Sao_Paulo

    install:

        # id identificador do ambiente numero unico para diferenciar as bases solr e banco
        # ATENCAO PRESTAR ATENCAO NESTA STRING
        # o as bases de dados sei e solr terao esse id no nome
        # caso instale o mesmo id com a opcao de reconstruir o banco, a automacao ira apagar os dados
        idInstalacao: "orgao1"

        db:
            # se enable vai criar um database para o sei e sip no banco
            # se disable crie manualmente seguindo a nomenclatura do instalador
            enable: true
            # indica se a automacao irah dropar e criar a base de dados
            # que foi informada para essa instancia
            recreate: true

        solr:
            # enable: true vai montar um job no namespace do solr informado
            # e criar os indices para esta instancia
            # caso nao deseje essa automacao coloque false e provisione os indices manualmente
            enable: true
            # Necessario para o instalador criar indice no solr para esta instancia
            namespace: solrnamespace

        sei:
            # se enable roda o instalador do sei a primeira vez q o ambiente subir
            # para instalar o sei e modulos
            # se desabilitado vc tera q rodar manualmente os instaladores
            enable: true

        ldap:
            # se true vai habilitar o orgao 0 no ldap
            enable: false
            # nome descritivo para o servidor (tela de cadastro de servidor ldap)
            nome: meuLdap
            # LDAP ou AD
            tipo: LDAP
            # nao altere, vai usar o servico ldap, o nome ou ip vai buscar do app.servicoExterno
            # definido mais acima
            endereco: ldap
            porta: 389
            sufixo:
            usuarioPesquisa: "cn=admin,dc=pen,dc=gov,dc=br"
            senhaPesquisa: "entrecomsenhadoldap"
            contextoPesquisa: "dc=pen,dc=gov,dc=br"
            filtroPesquisa: uid
            retornoPesquisa: distinguishedName
            # versao do AD ou ldap
            numeroVersao: 3


    host: meusei.br
    orgao: ORGAO1
    orgao_descricao: Orgao Helm1
    nome_complemento: Orgao Helm1
    memcached_host: memcached
    # indica se o memcached armazena a sessao do php, dispensando o sticky session
    memcached_session: "true"
    db_tipo: MySql
    db_host: db
    solr_url: http://solr:8983/solr
    solr_tempo_commit_protocolos: 30
    solr_tempo_commit_base_conhecimento: 300
    solr_tempo_commit_publicacoes: 300
    mail_tipo: 2
    mail_servidor: mail
    mail_codificacao: 8bit
    mail_maxdestinatarios: 999
    mail_max_tamanho_anexos: 999
    mail_protegido: ""

    federacao_habilitar: false

    servico_pd_instalar: false
    servico_pd_sigla: GOV.BR
    servico_pd_nome: protocolo.gov.br
    servico_pd_operacoes: 3,2,15,0,1

    modulo_estatisticas_instalar: true
    modulo_estatisticas_versao: "master"
    modulo_estatisticas_url: "https://estatistica.dev.processoeletronico.gov.br"
    modulo_estatisticas_sigla: "SEIPUBLICO"
    modulo_estatisticas_chave: "seipublico"

    modulo_resposta_instalar: false

    modulo_assinatura_instalar: false
    modulo_assinatura_urlprovider: "https://cas.staging.iti.br/oauth2.0"
    modulo_assinatura_clientid: "assinaturaavancadaxxx"
    modulo_assinatura_secret: "xxx"
    modulo_assinatura_validar_api_url: "https://h-api.iti.gov.br/validar/v3/validar"
    modulo_assinatura_validar_api_key: "xxxx"
    modulo_assinatura_token_url: "xxxx"
    modulo_assinatura_token_url_assinar: "xxxx"
    modulo_assinatura_integra_icp_url: "https://assinagov.staging.iti.br/assinador/v2/signer/integraICP"
    modulo_assinatura_integra_icp_url_clearings: "/get-clearings"
    modulo_assinatura_integra_icp_url_assinar: "/sign"
    modulo_assinatura_cloud_psc_url: "https://assinagov.staging.iti.br/assinador/v2/signer/cloud"
    modulo_assinatura_cloud_psc_url_start: "/start"
    modulo_assinatura_cloud_psc_url_assinar: "/sign"
    modulo_assinatura_api_key_ithy: "xxxx"

    modulo_pen_instalar: false
    modulo_pen_versao: "master"
    modulo_pen_webservice: "https://homolog.api.processoeletronico.gov.br/interoperabilidade/soap/v3/"
    modulo_pen_certificado_senha: "1234"
    modulo_pen_certificado_base64: "YXNkZgo="
    modulo_pen_repositorio_origem: ""
    modulo_pen_tipo_processo_externo: ""
    modulo_pen_unidade_geradora: ""
    modulo_pen_unidade_associacao_pen: ""
    modulo_pen_unidade_associacao_sei: ""


    # secrets
    db_porta: "3306"
    db_root_password: P@ssword
    db_root_username: root

    db_sei_username: "c2VpX3VzZXI="
    db_sei_password: "c2VpX3VzZXI="

    db_sip_password: "c2lwX3VzZXI="
    db_sip_username: "c2lwX3VzZXI="

    solrAdminUser: "admin"
    solrAdminPass: "SolrAdmin123$"

    mail_autenticar: "false"
    mail_porta: "25"

    mail_seguranca: ""
    mail_usuario: ""
    mail_senha: ""
    sei_chave_acesso: "7babf862e12bd48f3101075c399040303d94a493c7ce9306470f719bb453e0428c6135dc"
    sip_chave_acesso: "d27791b894028d9e7fa34887ad6f0c9a2c559cccda5f64f4e108e3573d5db862b66fb933"