app:

    # informe a classe do pvc onde serao criados os volumes do SEI
    # deve estar pre-instalado no seu kubernetes um provisionador nfs
    # gluster ou outro. No caso do docker-desktop ja existe um provisionador
    # automatico que cria uma pasta na vm do host ou do linux wsl. Para isso deixe
    # o storageclass vazio
    # caso contrario tera q criar o pv manualmente
    storage:
        #storageClass: nfs-client
        storageClass: ""

    # imagem para o php
    imagePhp:
        repository: ghcr.io/pengovbr/sei-helm/php
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry

    # imagem para o agendador
    imageCron:
        repository: ghcr.io/pengovbr/sei-helm/php-cron
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry

    # imagem para o servidor web (atualmente apache)
    imageWeb:
        repository: ghcr.io/pengovbr/sei-helm/apache
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry

    # imagem para rodar os jobs de instalacao / atualizacao
    imageInstall:
        repository: ghcr.io/pengovbr/sei-helm/php-install
        pullPolicy: IfNotPresent
        tag: 0.5.0
        # secret cadastrado no kube para o registry
        secret: secregistry


    pvc:
      # caso queira usar um seletor no pvc
      # para fazer o bind no PV, use como ex abaixo
      # seletor atual desabilidado
      selector: {}
      # para habilitar seque exemplo abaixo
      # Ex:
      # selector:
      #   matchLabels:
      #     purpose: app



    nameOverride: ""
    fullnameOverride: ""

    ingress:
        proxyBodySize: 510m

        # Nome do secret com o certificado TLS para o ingress.
        # Crie esse secret com antecedencia para o ingress caso
        # nao possua uma ferramenta emissora.
        # Adicione no formato crt e key padrao para ingress do kube
        tls_secret_name: "mysecret"

        # anotacoes opcionais, renomeie de zopcionais para opcionais,
        # apos isso, todos as anotacoes listadas serao publicadas no ingress
        # alem dos exemplos abaixo, vc pode informar as suas especificas
        zopcionais:
            #cert-manager.io/cluster-issuer: letsencrypt-dth
            #kubernetes.io/ingress.class: nginx
            #kubernetes.io/tls-acme: "true"
            #nginx.ingress.kubernetes.io/affinity: cookie1
            #nginx.ingress.kubernetes.io/session-cookie-name: PIINGRESSAFFINITY

    # endereco (nome) onde encontram-se os servicos externos
    servicoExterno:
        db: dbhostname
        jod: jodhostname
        solr: solrhostname
        memcached: memcachedhostname
        # nome ou ip
        mail: mailhostname
        ldap: ldaphostname

    tz: America/Sao_Paulo

    db:
        # nome pass das bases a conectar
        sipDbName: "siporg1"
        seiDbName: "seiorg1"
        sipUser: "usiporg1"
        sipPassword: "usiporg1"
        seiUser: "useiorg1"
        seiPassword: "useiorg1"

        db_porta: "3306"
        db_tipo: MySql
        # preferencia usar a chave servicoExterno acima
        db_host: db

        # user do banco com permissao para criar / alterar databases
        # usado pelos jobs de instalacao e atualizacao
        # apos os jobs rodarem vc podera desabilita-los no banco
        db_root_password: P@ssword
        db_root_username: root

        # se enable vai criar um database para o sei e sip no banco
        # se disable crie manualmente seguindo a nomenclatura do instalador
        criarDatabases: true

        # indica se a automacao irah dropar e criar a base de dados
        # que foi informada para essa instancia
        apagarDatabases: true

        sei_chave_acesso: "7babf862e12bd48f3101075c399040303d94a493c7ce9306470f719bb453e0428c6135dc"
        sip_chave_acesso: "d27791b894028d9e7fa34887ad6f0c9a2c559cccda5f64f4e108e3573d5db862b66fb933"

    solr:
        # nomes dos indices solr q a instancia vai usar
        idxProtocolo: org1sei-protocolos
        idxBaseConhecimento: org1sei-base-conhecimento
        idxPublicacoes: org1sei-publicacoes

        # tempos de commit dos indices
        # obrigatorio mesmo que enable: false, acima
        idxProtocoloTime: 150
        idxBaseConhecimentoTime: 300
        idxPublicacoesTime: 300

        # usuario e senha que o sei vai usar para acesar o solr
        username: org1solr
        password: org1solrp

        # preferencia usar a chave servicoExterno acima
        solr_url: http://solr:8983/solr


    # se enable roda o instalador do sei a primeira vez q o ambiente subir
    # para instalar o sei
    # se desabilitado vc tera q rodar manualmente os instaladores
    seiInstaladorInicial: true

    ldap:
        # se true vai habilitar o orgao 0 no ldap
        enable: false
        # nome descritivo para o servidor (tela de cadastro de servidor ldap)
        nome: meuLdap
        # LDAP ou AD
        tipo: LDAP
        # nao altere, vai usar o servico ldap, o nome ou ip vai buscar do app.servicoExterno
        # definido mais acima
        endereco: ldap
        porta: 389
        sufixo:
        usuarioPesquisa: "cn=admin,dc=pen,dc=gov,dc=br"
        senhaPesquisa: "entrecomsenhadoldap"
        contextoPesquisa: "dc=pen,dc=gov,dc=br"
        filtroPesquisa: uid
        retornoPesquisa: distinguishedName
        # versao do AD ou ldap
        numeroVersao: 3


    host: meusei.br
    orgao: ORGAO1
    orgao_descricao: Orgao Helm1
    nome_complemento: Orgao Helm1
    memcached_host: memcached
    # indica se o memcached armazena a sessao do php, dispensando o sticky session
    memcached_session: "true"

    mail:
        tipo: 2
        # preferencia usar a chave servicoExterno acima
        servidor: mail
        codificacao: 8bit
        maxdestinatarios: 999
        max_tamanho_anexos: 999
        protegido: ""
        autenticar: "false"
        porta: "25"
        seguranca: ""
        usuario: ""
        senha: ""

    mod_estatistica:
        instalar: true
        url: "https://estatistica.dev.processoeletronico.gov.br"
        sigla: "SEIPUBLICO"
        chave: "seipublico"

    mod_resposta:
        instalar: false

    mod_assinatura:
        instalar: false
        urlprovider: "https://cas.staging.iti.br/oauth2.0"
        clientid: "assinaturaavancadaxxx"
        secret: "xxx"
        validar_api_url: "https://h-api.iti.gov.br/validar/v3/validar"
        validar_api_key: "xxxx"
        token_url: "xxxx"
        token_url_assinar: "xxxx"
        integra_icp_url: "https://assinagov.staging.iti.br/assinador/v2/signer/integraICP"
        integra_icp_url_clearings: "/get-clearings"
        integra_icp_url_assinar: "/sign"
        cloud_psc_url: "https://assinagov.staging.iti.br/assinador/v2/signer/cloud"
        cloud_psc_url_start: "/start"
        cloud_psc_url_assinar: "/sign"
        api_key_ithy: "xxxx"

    mod_pen:
        instalar: false
        versao: "master"
        webservice: "https://homolog.api.processoeletronico.gov.br/interoperabilidade/soap/v3/"
        certificado_senha: "1234"
        # passe aqui o cert do tramita em base64
        certificado_base64: "YXNkZgo="
        # num do repo origem
        repositorio_origem: ""
        # id do tipo de  processo no sei
        tipo_processo_externo: ""
        # id da unidade do sei q vai receber inicialmente os processos
        unidade_geradora: ""
        # id da unidade no Tramita
        unidade_associacao_pen: ""
        # id da unidade do sei para enviar procs
        unidade_associacao_sei: ""
