apiVersion: v1
data:
  SOLR_PROBE_USER: {{ .Values.solr.solrProbeUser | b64enc }}
  SOLR_PROBE_PASS: {{ .Values.solr.solrProbePass | b64enc }}
kind: Secret
metadata:
  name: se-solr
  labels:
    {{- include "sei-solr.labels" . | nindent 4 }}
type: Opaque