apiVersion: v1
data:
{{- $cc := dict "user" .Values.solr.jobInstall.solrAdminUser "pass" .Values.solr.jobInstall.solrAdminPass }}
{{- range .Values.solr.jobInstall.orgaos }}
{{- $coc := merge . $cc }}
  solrcreate-{{ .orgao }}.sh: {{ tpl ($.Files.Get "apoio/scripts/solrcreate.sh") $coc | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: se-solr-install-files
  labels:
    {{- include "sei-solr.labels" . | nindent 4 }}
type: Opaque