################################################################################
# Memcached Oficial - apenas redundancia do repo oficial
################################################################################

ARG MEMCACHED_ORIGINAL_VERSION=1.6.40-alpine

FROM memcached:${MEMCACHED_ORIGINAL_VERSION}