################################################################################
# Memcached Oficial - apenas redundancia do repo oficial
################################################################################

ARG IMAGE_MEMCACHED_BASE=rodepleomakefile
ARG IMAGE_MEMCACHED_BASE_VERSION=rodepleomakefile

FROM ${IMAGE_MEMCACHED_BASE}:${IMAGE_MEMCACHED_BASE_VERSION}