################################################################################
# Alpine Oficial - apenas redundancia do repo oficial
################################################################################

ARG NGINX_ORIGINAL_VERSION=1.29.3

FROM nginx:${NGINX_ORIGINAL_VERSION}
