solr:

    # informe a classe do pvc onde sera criado o volume do solr
    # deve estar pre-instalado no seu kubernetes um provisionador nfs
    # gluster ou outro. No caso do docker-desktop ja existe um provisionador
    # automatico que cria uma pasta na vm do host ou do linux wsl. Para isso deixe
    # o storageclass vazio
    # caso contrario tera q criar o pv manualmente
    storage:
        #storageClass: nfs-client
        storageClass: ""

    tz: America/Sao_Paulo

    image:
        repository: ghcr.io/pengovbr/sei-helm/solr
        pullPolicy: IfNotPresent
        tag: "0.5.0"



    nameOverride: ""
    fullnameOverride: ""
