apiVersion: batch/v1
kind: Job
metadata:
  name: sei-solrcreate-{{ .Values.app.install.idInstalacao | lower }}
  namespace: {{ .Values.app.install.solr.namespace }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sei-solrcreate-{{ .Values.app.install.idInstalacao | lower }}
        {{- include "sei-app.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.app.imageInstall.secret }}
      containers:
      - command:
        - /seiscripts/solrcreate.sh
        image: {{ .Values.app.imageInstall.repository }}:{{ .Values.app.imageInstall.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.app.imageInstall.pullPolicy }}
        name: sei-solrcreate-{{ .Values.app.install.idInstalacao | lower }}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /seiscripts
          name: solrcreate
        - mountPath: /var/solr/data
          name: vol3
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - name: solrcreate
        configMap:
          name: cm-solrcreate-{{ .Values.app.install.idInstalacao | lower }}
          defaultMode: 0755
      - name: vol3
        persistentVolumeClaim:
          claimName: vol-sei-solr
