#orgao: orgaon
cacheassets:

    image:
        repository: ghcr.io/pengovbr/sei-helm/nginx
        pullPolicy: IfNotPresent
        tag: "0.5.0"

        # secret cadastrado no kube para o registry
        secret: secregistry

    nameOverride: ""
    fullnameOverride: ""

    # ========================
    # IMPORTANTE
    # ========================
    # informe aqui o backend de cada instalacao
    # o cache dos assets sera feito de forma independente para cada instancia
    # o mesmo nginx podera fazer o cache para todas as instancias do mesmo cluster
    # no array abaixo de backends informe o namespace e o host de cada instancia
    # caso o nginx n encontre um backend ele vai conectar no primeiro da lista abaixo
    # para tentar fazer o cache do asset

    backends:
        - namespace: default
          host: localhost
        #- namespace: app2
        #  host: sei2.teste
        #- namespace: nsorgao1
        #  host: orgao1.gov.br

app:

    host: meusei.br

    ingress:

        # Nome do secret com o certificado TLS para o ingress.
        # Crie esse secret com antecedencia para o ingress caso
        # nao possua uma ferramenta emissora.
        # Adicione no formato crt e key padrao para ingress do kube
        tls_secret_name: "mysecret"
