# Arquivo sugestivo. Sera sobrescrito pelo seu file no helm

ServerTokens Prod

ServerName https://localhost

KeepAlive On
MaxKeepAliveRequests 1000
KeepAliveTimeout 15
HostnameLookups Off
ServerSignature Off

Alias "/sei" "/opt/sei/web"
Alias "/sip" "/opt/sip/web"
Alias "/infra_css" "/opt/infra/infra_css"
Alias "/infra_js" "/opt/infra/infra_js"
Alias "/android-icon-192x192.png" "/opt/sei/web/favicon/android-icon-192x192.png"
Alias "/android-icon-512x512.png" "/opt/sei/web/favicon/android-icon-512x512.png"
Alias "/apple-touch-icon.png" "/opt/sei/web/favicon/apple-touch-icon.png"
Alias "/favicon.ico" "/opt/sei/web/favicon/favicon.ico"
Alias "/favicon.svg" "/opt/sei/web/favicon/favicon.svg"
Alias "/site.webmanifest" "/opt/sei/web/favicon/site.webmanifest"

LogFormat "%h %{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

<FilesMatch "\.(php)$">
    SetHandler "proxy:fcgi://php:9000"
</FilesMatch>

Protocols h2c http/1.1

SetEnvIfNoCase user-agent "Microsoft Data Access Internet Publishing Provider Protocol Discovery" bad_bot=1
<FilesMatch "(.*)">
   Order Allow,Deny
   Allow from all
   Deny from env=bad_bot
</FilesMatch>

#SetEnvIf X-Forwarded-Proto "https" HTTPS=on
#SetEnvIf X-Forwarded-Proto "https" HTTP_X_FORWARDED_PROTO=https

<VirtualHost *:80>
    DocumentRoot /opt
    ServerAdmin admin@dominio.gov.br


    DirectoryIndex index.php
    IndexIgnore *
    EnableSendfile Off
    HostnameLookups Off
    AddDefaultCharset iso-8859-1

    Header edit Location ^http://(.*)$ https://$1

    H2Direct on

    <Directory />
        AllowOverride None
        Require all denied
    </Directory>

    <Directory ~ "(/opt/sei/web|/opt/sip/web|/opt/infra/infra_css|/opt/infra/infra_js)" >
        AllowOverride None
        Options None
        Require all granted
    </Directory>

</VirtualHost>