apiVersion: v1
binaryData:
  instalar.sh: |-
    {{ tpl (.Files.Get "apoio/scripts/instalar.sh") . | b64enc }}
  sip-config-openldap.php: |-
    {{ tpl (.Files.Get "apoio/scripts/ldap/sip-config-openldap.php") . | b64enc }}
kind: ConfigMap
metadata:
  name: cm-initial
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}