apiVersion: v1
binaryData:
  instalar.sh: |-
    {{ .Files.Get "apoio/scripts/instalar.sh" | b64enc }}
kind: ConfigMap
metadata:
  name: cm-initial
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}